// Generated by CoffeeScript 1.6.3
(function() {
  console.log("fire index.js");

  exports.index = function(req, res) {
    res.render('index', {
      title: 'Gemfarmer-Express Bootstrap'
    });
  };

}).call(this);
